### PR TITLE
Fix for M34WQ

### PR DESCRIPTION
**Pull request by nnamua**
Hey! First of all, thank you for your work.
I tried using the script with my M34WQ, but unfortunately, only the KVM switch worked.

Using Sidekick and wireshark, I found out that in my case, Sidekick only sends the property hex code in two bytes if necessary. I hope that this also works for your display, otherwise simply reject the request.

### CODE REVIEW

**Comment by WildFireFlum** [comment]
Since you're using sidekick, I assume you're running on windows, is this the case?
I'd like to add your monitor to a compatibility list.

**Comment by nnamua** [comment]
I can try it on windows later today, so far I have only tested in on macOS (I only used Sidekick on Windows to check the USB messages).

**Comment by WildFireFlum** [comment]
Thank you for the fix!

**Comment by nnamua** [comment]
You can add Windows in combination with the M34WQ to the tested environments aswell! Works great!

**Comment by WildFireFlum** [comment]
Added, I assumed you were using windows 11, was I correct?

**Comment by nnamua** [comment]
Yep, correct!

**Pull request merged**
